name: Cypress Develop

on: push

jobs:
    cypress-run:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            # - name: Install modules
            #   uses: npm install
            - name: Write the cypress env file
              run: |
                echo '${{ secrets.CYPRESS_ENV }}' > cypress.env.json                
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                command: npm run test